### ISSUE TITLE
Create Queue Time Graph and Run Time Graphs

### ISSUE THREAD

**Issue by kommav** [kommav/funcXVisualizeNCSA#18]

**Comment by benclifford** [comment]
![image](https://user-images.githubusercontent.com/280107/218329295-b3f09c07-cfca-4148-a1eb-2ae9cff4b957.png)

**Comment by kommav** [comment]
Histogram Implementation

**Comment by kommav** [comment]
Data Set I have does not have execution-start and execution-end tags. 

Need access to updated and more standardized funcx.sqlite3
